In [1]:
import numpy as np

In [11]:
#create list
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

arr1 = np.array([1,2,3,4,5,"amy"])
print(arr1,type(arr))

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2,arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'amy'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
